# Generated by Django 5.1.7 on 2025-03-29 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count_rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('type_of_room', models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Room'), ('house', 'House'), ('studio', 'Studio')], default='apartment', max_length=10, verbose_name='Выберите жильё')),
                ('active', models.BooleanField(default=True, verbose_name='Активное объявление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Фото')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
